### ISSUE TITLE
Why does LuaTelemetry widget not work on OpenTX firmware simulator?

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#22]
I tried running it by simulate opentx-tx16s, opentx-t16, opentx-x10 and opentx-x12s with OpenTX 2.3.10 and 2.3.11, but it doesn't show up on selecting page widget

**Comment by teckel12** [comment]
@wizardrnd This means that the install wasn't correct. Specifically, the Widgets folder move.  I'm running the widget/script on the simulator right now.

**Comment by wizardrnd** [comment]
What version of open-tx simulator and what tx target are you use?

**Comment by teckel12** [comment]
OpenTX Companion v2.2.4 and OpenTX 2.2V0018

**Comment by teckel12** [comment]
Sorry, should have @wizardrnd you.  Also, it's possible there's issues with the build in the INAV repo.  I've just released v1.7.3 here which updates some files that may cause issues.  The latest release can be found here:

https://github.com/teckel12/LuaTelemetry/releases/tag/v1.7.3

**Comment by wizardrnd** [comment]
I tested release 1.7.3 on OpenTX firmware simulators 2.3.9, 2.3.10, 2.3.11 with tx-targets opentx-tx16s and opentx-x12s, but it is still missing from the widgets list.
Try to test you project on listed above simulator versions.

**Comment by teckel12** [comment]
@wizardrnd LuaTelemetry is only tested on OpenTX 2.2 due to breaking changes in OpenTX 2.3.  If the INAV drama lifts, maybe I'll have time to make things compatible with OpenTX 2.3.

Also, try it on the X10 transmitter simulator.  That's actually what I use instead of the X10 and X16.  It could be issues with those specifically and not the version of OpenTX.

**Comment by wizardrnd** [comment]
I use the widget of this script on a "real" Radiomaster TX16S, which does not have OpenTX firmware lower than v2.3.9 - and the script works fine. I was only surprised that there is no way to check the work of new versions or nightbilds of the script on the firmware simulator.while other widgets work fine in the simulator.
